// <auto-generated />
using System;
using EasyMicroservices.TemplateGeneratorMicroservice.Database.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EasyMicroservices.TemplateGeneratorMicroservice.Migrations
{
    [DbContext(typeof(TemplateGeneratorContext))]
    [Migration("20240117200918_Add_InfluencedToVariableName_FormItemEventActionEntity")]
    partial class Add_InfluencedToVariableName_FormItemEventActionEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.ActionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JobName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("UniqueIdentity")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.HasKey("Id");

                    b.HasIndex("CreationDateTime");

                    b.HasIndex("DeletedDateTime");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationDateTime");

                    b.HasIndex("ParentId");

                    b.HasIndex("UniqueIdentity");

                    b.ToTable("Actions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDateTime = new DateTime(2024, 1, 17, 23, 39, 17, 974, DateTimeKind.Local).AddTicks(8630),
                            IsDeleted = false,
                            JobName = "OpenDialog",
                            OrderIndex = 0
                        },
                        new
                        {
                            Id = 2L,
                            CreationDateTime = new DateTime(2024, 1, 17, 23, 39, 17, 974, DateTimeKind.Local).AddTicks(8633),
                            IsDeleted = false,
                            JobName = "OpenResponsibleDialog",
                            OrderIndex = 0
                        },
                        new
                        {
                            Id = 3L,
                            CreationDateTime = new DateTime(2024, 1, 17, 23, 39, 17, 974, DateTimeKind.Local).AddTicks(8634),
                            IsDeleted = false,
                            JobName = "OpenPage",
                            OrderIndex = 0
                        },
                        new
                        {
                            Id = 4L,
                            CreationDateTime = new DateTime(2024, 1, 17, 23, 39, 17, 974, DateTimeKind.Local).AddTicks(8635),
                            IsDeleted = false,
                            JobName = "CallExternalApi",
                            OrderIndex = 0
                        },
                        new
                        {
                            Id = 5L,
                            CreationDateTime = new DateTime(2024, 1, 17, 23, 39, 17, 974, DateTimeKind.Local).AddTicks(8637),
                            IsDeleted = false,
                            JobName = "SendResult",
                            OrderIndex = 0
                        },
                        new
                        {
                            Id = 6L,
                            CreationDateTime = new DateTime(2024, 1, 17, 23, 39, 17, 974, DateTimeKind.Local).AddTicks(8638),
                            IsDeleted = false,
                            JobName = "Close",
                            OrderIndex = 0
                        });
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.EventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueIdentity")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.HasKey("Id");

                    b.HasIndex("CreationDateTime");

                    b.HasIndex("DeletedDateTime");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationDateTime");

                    b.HasIndex("UniqueIdentity");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDateTime = new DateTime(2024, 1, 17, 23, 39, 17, 974, DateTimeKind.Local).AddTicks(8576),
                            IsDeleted = false,
                            Name = "Click"
                        },
                        new
                        {
                            Id = 2L,
                            CreationDateTime = new DateTime(2024, 1, 17, 23, 39, 17, 974, DateTimeKind.Local).AddTicks(8603),
                            IsDeleted = false,
                            Name = "TextChanged"
                        },
                        new
                        {
                            Id = 3L,
                            CreationDateTime = new DateTime(2024, 1, 17, 23, 39, 17, 974, DateTimeKind.Local).AddTicks(8604),
                            IsDeleted = false,
                            Name = "ItemSelected"
                        });
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormDetailEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FormId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueIdentity")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreationDateTime");

                    b.HasIndex("DeletedDateTime");

                    b.HasIndex("FormId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationDateTime");

                    b.HasIndex("UniqueIdentity");

                    b.ToTable("FormDetails");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueIdentity")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.HasKey("Id");

                    b.HasIndex("CreationDateTime");

                    b.HasIndex("DeletedDateTime");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationDateTime");

                    b.HasIndex("UniqueIdentity");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormFilledEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FormId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueIdentity")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.HasKey("Id");

                    b.HasIndex("CreationDateTime");

                    b.HasIndex("DeletedDateTime");

                    b.HasIndex("FormId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationDateTime");

                    b.HasIndex("UniqueIdentity");

                    b.ToTable("FormFills");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemActionJobEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ActionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FormItemId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UniqueIdentity")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("CreationDateTime");

                    b.HasIndex("DeletedDateTime");

                    b.HasIndex("FormItemId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationDateTime");

                    b.HasIndex("UniqueIdentity");

                    b.ToTable("FormItemActionJobs");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("FormId")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("ItemTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("LocalVariableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ParentFormItemId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PrimaryFormItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniqueIdentity")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.HasKey("Id");

                    b.HasIndex("CreationDateTime");

                    b.HasIndex("DeletedDateTime");

                    b.HasIndex("FormId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("ModificationDateTime");

                    b.HasIndex("ParentFormItemId");

                    b.HasIndex("PrimaryFormItemId");

                    b.HasIndex("UniqueIdentity");

                    b.ToTable("FormItems");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEventActionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ActionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long?>("FormItemEventActionEntityId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FormItemEventId")
                        .HasColumnType("bigint");

                    b.Property<long?>("FormItemId")
                        .HasColumnType("bigint");

                    b.Property<string>("InfluencedToVariableName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("UniqueIdentity")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("CreationDateTime");

                    b.HasIndex("DeletedDateTime");

                    b.HasIndex("FormItemEventActionEntityId");

                    b.HasIndex("FormItemEventId");

                    b.HasIndex("FormItemId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationDateTime");

                    b.HasIndex("UniqueIdentity");

                    b.ToTable("FormItemEventActions");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEventActionExecutionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FormItemEventActionId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequestJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("UniqueIdentity")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.HasKey("Id");

                    b.HasIndex("CreationDateTime");

                    b.HasIndex("DeletedDateTime");

                    b.HasIndex("FormItemEventActionId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationDateTime");

                    b.HasIndex("UniqueIdentity");

                    b.ToTable("FormItemEventActionCallHistories");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<long>("FormItemId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UniqueIdentity")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.HasKey("Id");

                    b.HasIndex("CreationDateTime");

                    b.HasIndex("DeletedDateTime");

                    b.HasIndex("EventId");

                    b.HasIndex("FormItemId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationDateTime");

                    b.HasIndex("UniqueIdentity");

                    b.ToTable("FormItemEvents");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemValueEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("FormFilledId")
                        .HasColumnType("bigint");

                    b.Property<long>("FormItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UniqueIdentity")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreationDateTime");

                    b.HasIndex("DeletedDateTime");

                    b.HasIndex("FormFilledId");

                    b.HasIndex("FormItemId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationDateTime");

                    b.HasIndex("UniqueIdentity");

                    b.ToTable("FormItemValues");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.ItemTypeEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<string>("UniqueIdentity")
                        .HasColumnType("nvarchar(450)")
                        .UseCollation("SQL_Latin1_General_CP1_CS_AS");

                    b.HasKey("Id");

                    b.HasIndex("CreationDateTime");

                    b.HasIndex("DeletedDateTime");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ModificationDateTime");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.HasIndex("UniqueIdentity");

                    b.ToTable("ItemTypes");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "DateTime",
                            Type = (byte)10
                        },
                        new
                        {
                            Id = 2L,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "DateOnly",
                            Type = (byte)11
                        },
                        new
                        {
                            Id = 3L,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "TimeOnly",
                            Type = (byte)12
                        },
                        new
                        {
                            Id = 4L,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Label",
                            Type = (byte)13
                        },
                        new
                        {
                            Id = 5L,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "CheckBox",
                            Type = (byte)8
                        },
                        new
                        {
                            Id = 6L,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "CheckList",
                            Type = (byte)7
                        },
                        new
                        {
                            Id = 7L,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "OptionList",
                            Type = (byte)9
                        },
                        new
                        {
                            Id = 8L,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "TextBox",
                            Type = (byte)6
                        },
                        new
                        {
                            Id = 9L,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Table",
                            Type = (byte)14
                        },
                        new
                        {
                            Id = 10L,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Row",
                            Type = (byte)15
                        },
                        new
                        {
                            Id = 11L,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "AutoIncrementNumber",
                            Type = (byte)16
                        },
                        new
                        {
                            Id = 12L,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Column",
                            Type = (byte)17
                        },
                        new
                        {
                            Id = 13L,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Menu",
                            Type = (byte)18
                        },
                        new
                        {
                            Id = 14L,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Card",
                            Type = (byte)19
                        },
                        new
                        {
                            Id = 15L,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "Button",
                            Type = (byte)20
                        },
                        new
                        {
                            Id = 16L,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "HorizontalStack",
                            Type = (byte)21
                        },
                        new
                        {
                            Id = 17L,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "VerticalStack",
                            Type = (byte)22
                        },
                        new
                        {
                            Id = 18L,
                            CreationDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Title = "VerticalStack",
                            Type = (byte)23
                        });
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.ActionEntity", b =>
                {
                    b.HasOne("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.ActionEntity", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormDetailEntity", b =>
                {
                    b.HasOne("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormEntity", "Form")
                        .WithMany("FormDetails")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormFilledEntity", b =>
                {
                    b.HasOne("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormEntity", "Form")
                        .WithMany("FormFills")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Form");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemActionJobEntity", b =>
                {
                    b.HasOne("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.ActionEntity", "Action")
                        .WithMany("FormItemActionJobs")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEntity", "FormItem")
                        .WithMany("FormItemActionJobs")
                        .HasForeignKey("FormItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("FormItem");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEntity", b =>
                {
                    b.HasOne("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormEntity", "Form")
                        .WithMany("FormItems")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.ItemTypeEntity", "ItemType")
                        .WithMany("FormItems")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEntity", "ParentFormItem")
                        .WithMany("Children")
                        .HasForeignKey("ParentFormItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEntity", "PrimaryFormItem")
                        .WithMany("PrimaryFormItems")
                        .HasForeignKey("PrimaryFormItemId");

                    b.Navigation("Form");

                    b.Navigation("ItemType");

                    b.Navigation("ParentFormItem");

                    b.Navigation("PrimaryFormItem");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEventActionEntity", b =>
                {
                    b.HasOne("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.ActionEntity", "Action")
                        .WithMany("FormItemEventActions")
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEventActionEntity", null)
                        .WithMany("Children")
                        .HasForeignKey("FormItemEventActionEntityId");

                    b.HasOne("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEventEntity", "FormItemEvent")
                        .WithMany("FormItemEventActions")
                        .HasForeignKey("FormItemEventId");

                    b.HasOne("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEntity", "FormItem")
                        .WithMany()
                        .HasForeignKey("FormItemId");

                    b.Navigation("Action");

                    b.Navigation("FormItem");

                    b.Navigation("FormItemEvent");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEventActionExecutionEntity", b =>
                {
                    b.HasOne("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEventActionEntity", "FormItemEventAction")
                        .WithMany("FormItemEventActionCallHistories")
                        .HasForeignKey("FormItemEventActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormItemEventAction");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEventEntity", b =>
                {
                    b.HasOne("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.EventEntity", "Event")
                        .WithMany("FormItemEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEntity", "FormItem")
                        .WithMany("FormItemEvents")
                        .HasForeignKey("FormItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("FormItem");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemValueEntity", b =>
                {
                    b.HasOne("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormFilledEntity", "FormFilled")
                        .WithMany("FormItemValues")
                        .HasForeignKey("FormFilledId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEntity", "FormItem")
                        .WithMany("FormItemValues")
                        .HasForeignKey("FormItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FormFilled");

                    b.Navigation("FormItem");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.ActionEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("FormItemActionJobs");

                    b.Navigation("FormItemEventActions");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.EventEntity", b =>
                {
                    b.Navigation("FormItemEvents");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormEntity", b =>
                {
                    b.Navigation("FormDetails");

                    b.Navigation("FormFills");

                    b.Navigation("FormItems");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormFilledEntity", b =>
                {
                    b.Navigation("FormItemValues");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("FormItemActionJobs");

                    b.Navigation("FormItemEvents");

                    b.Navigation("FormItemValues");

                    b.Navigation("PrimaryFormItems");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEventActionEntity", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("FormItemEventActionCallHistories");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.FormItemEventEntity", b =>
                {
                    b.Navigation("FormItemEventActions");
                });

            modelBuilder.Entity("EasyMicroservices.TemplateGeneratorMicroservice.Database.Entities.ItemTypeEntity", b =>
                {
                    b.Navigation("FormItems");
                });
#pragma warning restore 612, 618
        }
    }
}
